# Generated by Django 3.2.15 on 2024-01-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='baggage_number',
            field=models.CharField(default=12345, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
