# Generated by Django 3.2.15 on 2024-01-28 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20240129_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=1000000),
        ),
    ]
