# Generated by Django 3.2.15 on 2024-01-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
